### ISSUE TITLE
D. a) Send yearly reminder to update or archive entry

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kvm-welcome-email#2]
>  Microservice (Cronejobe mit Admin-Acccount für Backend) aufsetzen, der checkt, welche Einträge seit einem Jahr nicht mehr aktualisiert wurden, deren Status auf unconfirmed setzt und eine Mailnotification an den Eintrag auslöst 

# Problem
After 5 years of running this map we have a lot of outdated entries there

# Solution
- If an entry was not updated or modified for W (=365) days, write an email (same way like when they are added https://github.com/kartevonmorgen/openfairdb/issues/333) to the entry-mailadress, that it was not modified or rated since W (=365) days, with title: Please update your entry now! 

Mail contains: 
  - A) an informational text See mailtext here: https://cloud.wechange.de/s/iBoSGDgTdAmQE4D
  - B) all current fields of the entry and 
    - Ist all das noch aktuell?
  - C) three links: (with token https://github.com/kartevonmorgen/openfairdb/issues/396)
    1. **Update Entry now** (would redirect to the opened entry form to update https://kartevonmorgen.org/#/?entry=ae76a54a419443fcb542b395d01ec6c9**&editentry**
    2. **Entry is still up to date** (link to the entry with a certain token, that will just edit the status to "confirmed")
    3. **Archive this entry** (will directly archive/ delete this entry form the map)

Um das Mailtemplate anpassen zu können braucht es ein Editor, wie jetzt schon auf https://kvmmail.shiv.uber.space/ für die Begrüßungsmails.

- If an entry was not updated or modified for X (=400) days, send an email to the pilots: https://github.com/kartevonmorgen/kvm-email-notification/issues/3
- Take out the colour of the pin and just leave the contour, if the entry was not edited for X (=690) days (-> frontend issue) https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/139

# Steps
Update-Reminder and DB-Processing are complete independent steps:
## Update Reminder
1. Microservice (Cronejobe mit Admin-Acccount für Backend) that checks the last editing-dates of entries -> if more than one year not edited -> set entry as "uncomfirmed" 
2. If status set to unconfirmed -> Mailingservice sends mails first to entries -> ask to confirm or update or achive (Mailgun ist schon eingereichtet)  https://github.com/kartevonmorgen/openfairdb/issues/202
4. If 400 days  uncomfirmed and not edited -> send to pilots (Connected to Algorythmus of Subscriptions) -> ask to confirm or update or achive (https://github.com/kartevonmorgen/openfairdb/issues/166) 1Tag

## Independently the frontend will grey-out outdated pins
0. Datenbank so einstellen, dass Einträge, die seit über 800 Tagen nicht beantwortet wurden, auch nur noch grau sind.

**Comment by wellemut** [comment]
@flosse hier ist der Mailtext für den jährliche Erinnerung an Einträge: https://cloud.wechange.de/s/iBoSGDgTdAmQE4D

Kann man unten in der Mail in einer Art Signatur auch logos anzeigen? Im Markdown-Dokument ist das mal hinterlegt:

[![](https://blog.vonmorgen.org/wp-content/uploads/2022/11/Karte-von-morgen1-e1668006375192.png)](http://blog.vonmorgen.org/)[![](https://bildung.vonmorgen.org/wp-content/uploads/2018/10/Ideen_hoch_drei_Logo_RGB-1-300x116.png)](http://ideenhochdrei.org/)

**Comment by flosse** [comment]
done in https://github.com/kartevonmorgen/openfairdb/issues/439
