### ISSUE TITLE
D. b) Update-Erinnerung für Regional- und Themenpilot*innen einrichten

### ISSUE THREAD

**Issue by wellemut** [kartevonmorgen/kvm-welcome-email#3]
> Mailnotification für Regional- und Themenpilot*innen einrichten, für Einträge, die nach 400 Tagen immer noch nicht aktualisiert wurden

- Second step after: https://github.com/kartevonmorgen/kvm-welcome-email/issues/2
- Based on subscriptions on the map

if x=400 days an entry was not changed than:
-> Write a mail to anybody who has subscribed to the area (or the topic https://github.com/kartevonmorgen/kvmflows/issues/8) and to all who have updated the entry in the past. (https://github.com/kartevonmorgen/kartevonmorgen/issues/635)
Title: 
  - Update needed: [Name of the entry] 
  - And the body of the mail should contain all information of the entry (like the mailnotification about creation.): https://cloud.wechange.de/s/iBoSGDgTdAmQE4D

- Needs One-Time Edit links with tokens: https://github.com/kartevonmorgen/openfairdb/issues/396

Next Issue
- if there is still no change after ~700 days, then mark the pin as grey https://github.com/kartevonmorgen/kartevonmorgen.ts/issues/139

-----
### Issues which should be included:
- https://github.com/kartevonmorgen/kvmflows/issues/4

**Comment by wellemut** [comment]
Teil des Angebots für RENN Süd
![grafik](https://user-images.githubusercontent.com/15019030/179216547-4fc83f8d-2e2d-4634-a4cf-b6e163ac752f.png)

**Comment by wellemut** [comment]
@flosse die letzte Mail in diesem Dokument ist die Vorlage für Reminder an Piloten: https://cloud.wechange.de/s/iBoSGDgTdAmQE4D

**Comment by flosse** [comment]
I'd say we're done. Feel free to re-open if not!
